/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GTreeAPI */

#ifndef _Included_GTreeAPI
#define _Included_GTreeAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GTreeAPI
 * Method:    getDistanceVertexToVertex
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_GTreeAPI_getDistanceVertexToVertex
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GTreeAPI
 * Method:    getAllCanditateDist
 * Signature: (I[I)[LVertexDist;
 */
JNIEXPORT jobjectArray JNICALL Java_GTreeAPI_getAllCanditateDist
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     GTreeAPI
 * Method:    getAllCanditateDistWithExtraTimeReturn
 * Signature: (I[I)[LVertexDist;
 */
JNIEXPORT jobjectArray JNICALL Java_GTreeAPI_getAllCanditateDistWithExtraTimeReturn
  (JNIEnv *, jobject, jint, jintArray);

/*
 * Class:     GTreeAPI
 * Method:    getTopkGtreeNodes
 * Signature: (II)[LVertexDist;
 */
JNIEXPORT jobjectArray JNICALL Java_GTreeAPI_getTopkGtreeNodes
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GTreeAPI
 * Method:    getGtreeNodes
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GTreeAPI_getGtreeNodes
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GTreeAPI
 * Method:    getNearestNumsVertex
 * Signature: (II)[LVertexDist;
 */
JNIEXPORT jobjectArray JNICALL Java_GTreeAPI_getNearestNumsVertex
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     GTreeAPI
 * Method:    InitGtree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GTreeAPI_InitGtree
  (JNIEnv *, jobject);

/*
 * Class:     GTreeAPI
 * Method:    InitGtreeTimes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_GTreeAPI_InitGtreeTimes
  (JNIEnv *, jobject);

/*
 * Class:     GTreeAPI
 * Method:    getVertexByNodeK
 * Signature: (II)[LVertex;
 */
JNIEXPORT jobjectArray JNICALL Java_GTreeAPI_getVertexByNodeK
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
